<?xml version="1.0" encoding="utf-8"?><Database Name="BookLibrary" Class="BookLibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\BookLibrary.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BookLibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Authors" Member="Authors">
    <Type Name="Author">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Author_Book" Member="Books" ThisKey="Id" OtherKey="Author_Id" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Genres" Member="Genres">
    <Type Name="Genre">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Book" Member="Books" ThisKey="Id" OtherKey="Genre_Id" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Editorial" Member="Editorials">
    <Type Name="Editorial">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Editorial_Book" Member="Books" ThisKey="Id" OtherKey="Editorial_Id" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Genre_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Editorial_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Published_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Author_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Book" Member="Genre" ThisKey="Genre_Id" OtherKey="Id" Type="Genre" IsForeignKey="true" />
      <Association Name="Author_Book" Member="Author" ThisKey="Author_Id" OtherKey="Id" Type="Author" IsForeignKey="true" />
      <Association Name="Editorial_Book" Member="Editorial" ThisKey="Editorial_Id" OtherKey="Id" Type="Editorial" IsForeignKey="true" />
    </Type>
  </Table>
</Database>